<script type="text/javascript">
(function($){
	$(function(){
		jQuery('.adminhtml-wsu-logger-index td,a[href*="fulllogjson"]').on('click',function(e){
			e.stopPropagation();
			e.preventDefault();
			var row			= jQuery(this).closest('tr');
			var fullView	= row.find('a[href*="fulllogjson"]');
			if(jQuery( "#dialog-message" ).length<=0){
				var url = fullView.attr('href');
				jQuery.ajax({
					type: 'GET',
					 url: url,
					 async: false,
					 jsonpCallback: 'jsonCallback',
					 contentType: "application/json",
					 dataType: 'jsonp',
					 success: function(json) {
						html="";
						html +="entity_id :: "+json.entity_id+"<br/>";
						html +="admin_id :: "+json.admin_id+"<br/>";
						html +="customer_id :: "+json.customer_id+"<br/>";
						html +="timestamp :: "+json.timestamp+"<br/>";
						html +="message :: "+json.message+"<br/>";
						html +="trace :: "+json.trace+"<br/>";
						html +="priority :: "+json.priority+"<br/>";
						html +="priority_name :: "+json.priority_name+"<br/>";
						html +="file :: "+json.file+"<br/>";
	
						jQuery('body').append('<div id="dialog-message">'+html+'</div>');
					 },
					 error: function(e) {
						 jQuery('body').append('<div id="dialog-message">'+e.message+'</div>');	
					 }
				});
			}
			jQuery( "#dialog-message" ).dialog({
				modal: true,
				maxHeight:550,
				maxWidth:700,
				minHeight:350,
				minWidth:400,
				buttons: {
					Ok: function() {
						jQuery( this ).dialog( "close" );
					}
				},
				close:function( event, ui ){
					jQuery( this ).dialog( "destroy" );
					jQuery( "#dialog-message" ).remove();
				}
			});
		});
	});
})(jQuery);
/*
		
		
		
		
        var url = '<?php echo $this->getUrl('adminhtml/dashboard/index') ?>?';
        if ($('browser_window') && typeof(Windows) != 'undefined') {
            Windows.focus('browser_window');
            return;
        }
        var dialogWindow = Dialog.info(null, {
            closable:true,
            resizable:false,
            draggable:true,
            className:'magento',
            windowClassName:'popup-window',
            title:'Test popup Dialog',
            top:50,
            width:300,
            height:150,
            zIndex:1000,
            recenterAuto:false,
            hideEffect:Element.hide,
            showEffect:Element.show,
            id:'browser_window',
            url:url,
            onClose:function (param, el) {
                alert('onClose');
            }
        });
    }
    function closePopup() {
        Windows.close('browser_window');
    }

	*/
	
	
	
</script>    
