<style>
.issue_label{ font-weight:bold; }
.issue_content{ display:block; }

.stack_number{font-size:.95em; font-weight:400;}
.stack_item{
	font-size:.75em;
	font-style:italic;
}
.stack_header{
	font-weight:900;
}
</style>

<script type="text/javascript">
(function($){
	$(function(){
		jQuery('.adminhtml-wsu-auditing-index .grid td,a[href*="fulllogjson"]').on('click',function(e){
			e.stopPropagation();
			e.preventDefault();
			var row			= jQuery(this).closest('tr');
			var fullView	= row.find('a[href*="fulllogjson"]');
			var url = fullView.attr('href');
			
			if(typeof(url)!="undefined"){
				if(jQuery( "#dialog-message" ).length<=0){
					jQuery.ajax({
						type: 'GET',
						 url: url,
						 async: false,
						 jsonpCallback: 'jsonCallback',
						 contentType: "application/json",
						 dataType: 'jsonp',
						 success: function(json) {
							html="";
							html +="<span class='issue_label'>audit_id ::</span> <span class='issue_content'>"+json.audit_id+"</span>";
							html +="<span class='issue_label'>admin_id ::</span> <span class='issue_content'>"+json.admin_id+"</span>";
							html +="<span class='issue_label'>customer_id ::</span> <span class='issue_content'>"+json.customer_id+"</span>";
							html +="<span class='issue_label'>timestamp ::</span> <span class='issue_content'>"+json.timestamp+"</span>";
							
							var pattern = /(\s#\d+\s)/igm;
							message = json.message.replace( pattern, "<br/>&nbsp;&nbsp;&nbsp;&nbsp;<span class='stack_number'>$1</span><span class='stack_item'>" );
							var pattern = /(stack_item'>.*?<br\/>)/igm;
							message = message.replace( pattern, "$1</span>" );
							message = message.split('Stack trace:').join('<br/>&nbsp;&nbsp;<span class="stack_header"> Stack trace: </span>');
							html +="<span class='issue_label'>message ::</span> <span class='issue_content'>"+message+"</span></span>";
							
							 
							var pattern = /(\[\d+\])/igm;
							trace = json.trace.replace( pattern, "<br/>&nbsp;&nbsp;&nbsp;&nbsp;<span class='stack_number'>$1</span><span class='stack_item'>" );
							var pattern = /(stack_item'>.*?<br\/>)/igm;
							trace = trace.replace( pattern, "$1</span>" );
							html +="<span class='issue_label'>trace ::</span> <span class='issue_content'>"+trace+"</span></span>";
							html +="<span class='issue_label'>priority ::</span> <span class='issue_content'>"+json.priority+"</span>";
							html +="<span class='issue_label'>priority_name ::</span> <span class='issue_content'>"+json.priority_name+"</span>";
							html +="<span class='issue_label'>file ::</span> <span class='issue_content'>"+json.file+"</span>";
		
							jQuery('body').append('<div id="dialog-message">'+html+'</div>');
						 },
						 error: function(e) {
							 jQuery('body').append('<div id="dialog-message">'+e.message+'</div>');	
						 }
					});
				}
				jQuery( "#dialog-message" ).dialog({
					modal: true,
					maxHeight:550,
					maxWidth:700,
					minHeight:350,
					minWidth:400,
					width:$(window).width() * 0.75,
					open:function(){
						$('body').css({overflow:"hidden"});
					},
					buttons: {
						Ok: function() {
							jQuery( this ).dialog( "close" );
						}
					},
					close:function( event, ui ){
						jQuery( this ).dialog( "destroy" );
						jQuery( "#dialog-message" ).remove();
						if($(".ui-dialog.ui-widget.ui-widget-content").length<=0){
							$('body').css({overflow:"auto"});
						}
					}
				});
			}
		});
	});
})(jQuery);
/*
		
		
		
		
        var url = '<?php echo $this->getUrl('adminhtml/dashboard/index') ?>?';
        if ($('browser_window') && typeof(Windows) != 'undefined') {
            Windows.focus('browser_window');
            return;
        }
        var dialogWindow = Dialog.info(null, {
            closable:true,
            resizable:false,
            draggable:true,
            className:'magento',
            windowClassName:'popup-window',
            title:'Test popup Dialog',
            top:50,
            width:300,
            height:150,
            zIndex:1000,
            recenterAuto:false,
            hideEffect:Element.hide,
            showEffect:Element.show,
            id:'browser_window',
            url:url,
            onClose:function (param, el) {
                alert('onClose');
            }
        });
    }
    function closePopup() {
        Windows.close('browser_window');
    }

	*/
	
	
	
</script>    
