<?php
/**
 * @var $this Wsu_Logger_Block_Adminhtml_System_Config_Fieldset_Hint
 */
?>
<div class="box">
    <div style="background:url('<?=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)?>wsu-brand/bug-logotype.svg') no-repeat left top;padding-left:59px;min-height:59px;">
        <a href="https://github.com/washingtonstateuniversity/WSUMAGE-auditing" target="_blank" style="float:right;">
            <img src="<?=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA)?>wsu-brand/Github-fork-icon.svg" alt="Fork me on GitHub" title="Fork me on GitHub" />
        </a>
        <h4><?php echo $this->helper('wsu_logger')->__('Wsu Logger allows you to gain access to and creates logs.'); ?></h4>
        <p style="margin-bottom:0;"><?php echo $this->helper('wsu_logger')->__('Full overview available'); ?> <a href="<?php echo $this->escapeHtml($this->helper('wsu_logger')->__('#')); ?>" target="_blank"><?php echo $this->helper('wsu_logger')->__('here'); ?></a>.</p>
    </div>
	<p style="margin-bottom:0;"><?php echo $this->helper('wsu_logger')->__('There logs that are created over the defaults are Products history of changes, downloaded products, and API logs.  You will also be able to view all error and warning logs that are thrown system wide.'); ?>.</p>
</div>